### ISSUE TITLE
Spaces support

### ISSUE THREAD

**Issue by ShadowJonathan** [mautrix/whatsapp#296]
Haven't seen this issue in here, but... (private) Spaces support?

**Comment by frandavid100** [comment]
Would the bridge automatically create DMs for all your WhatsApp contacts and put them inside the space?

**Comment by tulir** [comment]
That's not related to spaces, it's already in the [config](https://github.com/tulir/mautrix-whatsapp/blob/v0.1.6/example-config.yaml#L125-L126)

**Comment by frandavid100** [comment]
Hi, Tulir. If I understand it correctly, that only creates rooms for the contacts with whom you've already started a conversation; not with all the contacts in your contact list.

Is that right?

**Comment by tulir** [comment]
The bridge won't open rooms for all contacts, but it will probably add the users to the space

**Comment by frandavid100** [comment]
That's great.

**Comment by christianlupus** [comment]
As far as I understand the [config](https://github.com/mautrix/whatsapp/blob/v0.1.6/example-config.yaml#L79-L86), the bridge uses communities currently. Just for clarification: Is this somehow already portable to spaces?
I tried it once and failed to see my old portals but this might be due to other errors on my side.

**Comment by speatzle** [comment]
I can find the config option in the v0.2.x releases

**Comment by sumnerevans** [comment]
Communities are deprecated by element. Spaces support hasn't been implemented yet in the bridge.

**Comment by jkhsjdhjs** [comment]
This is implemented via https://github.com/mautrix/whatsapp/pull/413, right?
