### ISSUE TITLE
Multi-device (beta) support

### ISSUE THREAD

**Issue by comigor** [mautrix/whatsapp#330]
Hi!
I've just joined WhatsApp multi-device beta program, which I assume uses a completely different API (specially given the [new way](https://faq.whatsapp.com/general/about-end-to-end-encryption) to handle end-to-end encryption), and it made this bridge stop working.

This feature could even avoid the need to have an amulator running for WhatsApp.

I'm creating this issue just to raise awareness of the beta.

[WhatsApp multi-device beta FAQ](https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta/?lang=en)

**Comment by Nothing4You** [comment]
from the FAQ:

> If you don’t use your phone for over 14 days, your linked devices will become disconnected.

so you will still need to have it connected *somewhere* and cannot get rid of the emulator, assuming you're not running WA on your regular phone.

does the multi device beta still require scanning QR codes to activate additional devices?
that's the main pain point of VMs for me at least.

**Comment by comigor** [comment]
>Does the multi device beta still require scanning QR codes to activate additional devices?

Sadly, yes. That's still the way to authenticate an account and now probably also what triggers the E2E keys generation.

**Comment by SeBaBu** [comment]
Some people started reverse engineering it. Just wanted to leave it here, could be useful: https://github.com/sigalor/whatsapp-web-multi-device-reveng

**Comment by micw** [comment]
According to https://github.com/Rhymen/go-whatsapp/issues/598, this would require a large refactoring of go-whatsapp which is unlikely to happen in near future.

I get the opinion that it would be more straight-forward to automate an embedded/headless browser to communicate with WhatsApp. This would have a lot of benefits (especially not breaking on every API change, _way_ easier implementation since no internal formats must be reverse-enginered).

Have a look at https://github.com/Kalebu/alright/blob/main/alright/__init__.py which is a relatively new implementation. The ammount of code to make ist sending messages is surpisingly small.

**Comment by tulir** [comment]
Headless browsers are way too hacky and use too much resources. Tried that with Google's Android Messages, not going to try it again.

mautrix-whatsapp will support multi-device natively in the near-ish future (although there's a chance it'll use a separate daemon if I don't manage to port everything to Go in time)

**Comment by micw** [comment]
> mautrix-whatsapp will support multi-device natively in the near-ish future

May I ask, which library you plan to use for this?
